# Generated by Django 4.2.1 on 2023-05-21 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0003_remove_bookraiting_rated_users_count_and_more'),
        ('usercart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercart',
            old_name='user_model_id',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='book_id',
        ),
        migrations.CreateModel(
            name='ListOfUsersPurchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'purchase',
                'verbose_name_plural': 'purchases',
            },
        ),
        migrations.AddField(
            model_name='cartitem',
            name='user_purchase_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usercart.listofuserspurchases'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='book_id',
            field=models.ManyToManyField(to='book.book'),
        ),
    ]
