# Generated by Django 4.2.1 on 2023-11-11 09:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_comment_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFavouriteBooks',
            new_name='UserFavoriteBooks',
        ),
    ]
