# Generated by Django 4.2.1 on 2023-11-12 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_staff', '0003_rename_userfavoritebooks_userlikedbooks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='cover_type',
            field=models.CharField(choices=[('PAPERBACK', 'paperback'), ('HARDCOVER', 'hardcover')], default='hardcover', max_length=9),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='cover_type',
            field=models.CharField(choices=[('PAPERBACK', 'paperback'), ('HARDCOVER', 'hardcover')], default='hardcover', max_length=9),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='user_purchases_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='user_staff.userpurchaseslist', verbose_name="related list of user's purchases"),
        ),
    ]
