# Generated by Django 4.2.1 on 2023-11-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_staff', '0005_alter_userlikedbooks_options_cartitem_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price',
            field=models.FloatField(default=19.99),
        ),
    ]
