# Generated by Django 4.2.1 on 2023-11-16 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_staff', '0006_alter_cartitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlikedbooks',
            name='user_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked', to=settings.AUTH_USER_MODEL, verbose_name='related user'),
        ),
    ]
