# Generated by Django 4.2.1 on 2023-11-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_staff', '0007_alter_userlikedbooks_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cover_type',
            field=models.CharField(default='hardcover', max_length=9),
        ),
    ]
