# Generated by Django 4.2.1 on 2023-10-27 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0001_initial'),
        ('user_favourite_books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavouriteBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favourite', to=settings.AUTH_USER_MODEL)),
                ('user_liked_books', models.ManyToManyField(blank=True, to='book.book')),
            ],
            options={
                'verbose_name': 'favourite',
                'verbose_name_plural': 'favourite',
            },
        ),
        migrations.DeleteModel(
            name='UserFavoriteBooks',
        ),
    ]
