# Generated by Django 4.2.1 on 2023-10-27 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_favourite_books', '0002_userfavouritebooks_delete_userfavoritebooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavouritebooks',
            name='user_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
