# Generated by Django 4.2.1 on 2023-05-21 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0002_alter_book_liked_by_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookraiting',
            name='rated_users_count',
        ),
        migrations.AlterField(
            model_name='bookraiting',
            name='score',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='bookraiting',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
