# Generated by Django 4.2.1 on 2023-11-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, default='djangodbmodelsfieldscharfield', max_length=255, unique=True, verbose_name='slug'),
        ),
    ]
