# Generated by Django 4.2.1 on 2023-05-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_remove_bookraiting_rated_users_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='in_sthock_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
