# Generated by Django 4.2.1 on 2023-11-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_remove_book_authors_author_something_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='something',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='book.author'),
        ),
    ]
