# Generated by Django 4.2.1 on 2023-05-21 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_in_sthock_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='in_sthock_quantity',
            new_name='in_stock_quantity',
        ),
    ]
