# Generated by Django 4.2.1 on 2023-11-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_book_cover_image_preview_alter_book_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image_preview',
            field=models.ImageField(upload_to='books/covers/', verbose_name='cover preview'),
        ),
    ]
