# Generated by Django 4.2.1 on 2023-05-21 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userfavoritebooks', '0001_initial'),
        ('book', '0006_remove_book_in_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='average_value',
        ),
        migrations.RemoveField(
            model_name='book',
            name='liked_by_user',
        ),
        migrations.AlterField(
            model_name='bookraiting',
            name='book_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.book'),
        ),
        migrations.AddField(
            model_name='book',
            name='liked_by_user',
            field=models.ManyToManyField(to='userfavoritebooks.userfavoritebooks'),
        ),
    ]
