# Generated by Django 4.2.1 on 2023-10-28 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_cart', '0002_alter_usercart_user_id_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='purchases_list',
        ),
    ]
