# Generated by Django 4.2.1 on 2023-10-28 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_comment'),
        ('user_cart', '0003_remove_cartitem_purchases_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='book.book'),
        ),
    ]
