# Generated by Django 4.2.1 on 2023-10-28 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_cart', '0004_alter_cartitem_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='user_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cart', to='user_cart.usercart'),
        ),
    ]
