# Generated by Django 4.2.1 on 2023-10-28 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_cart', '0005_alter_cartitem_user_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='user_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='user_cart.usercart'),
        ),
    ]
