# Generated by Django 4.2.1 on 2023-10-28 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_cart', '0007_alter_cartitem_book_purchaseitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchaseItem',
        ),
    ]
