# Generated by Django 4.2.1 on 2023-10-24 15:01

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='media/user/avatars/default_avatar.svg', null=True, upload_to=user.models.upload_to, verbose_name='Image'),
        ),
    ]
